[project]
name = "py-sse"
version = "0.5.0"
description = "minimal python sse server"
readme = "README.md"
authors = [
    { name = "Deufel", email = "MDeufel13@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "apsw>=3.53.1.0",
    "brotli>=1.2.0",
]

[build-system]
requires = ["uv_build>=0.11,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo-dev>=0.3.3",
    "marimo>=0.21.1",
]

[tool.marimo-dev]
  renames = {dunder_ = "__", internal_ = "_"}
  nbs = "notebooks"
  out = "src"
  skip_prefixes = ["XX_", "test_"]  # ignore these files
