[project]
name = "py-sse"
version = "0.2.1"
description = "opinionated application wrapper for granian"
readme = "README.md"
authors = [
    { name = "Deufel", email = "MDeufel13@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "apsw>=3.53.1.0",
    "granian>=2.7.2",
    "requests>=2.32.5",
]

[build-system]
requires = ["uv_build>=0.11,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo-dev>=0.3.3",
    "marimo>=0.21.1",
    "ngrok>=1.7.0",
]

[tool.marimo-dev]
  renames = {dunder_ = "__", internal_ = "_"}
  nbs = "notebooks"
  out = "src"
  skip_prefixes = ["XX_", "test_"]  # ignore these files
